### ISSUE TITLE
Failing to send email notifications

### ISSUE THREAD

**Issue by afairhurst** [putyourlightson/craft-sendgrid#1]
Hi Ben,

Thanks for creating this plug-in, however I have been unable to get it to work with either Simple Contact Form or Express Forms.

Test email button works (test received by SendGrid and email client), however when I submit a form nothing is received to SendGrid or my email address.

I've switched to SMTP instead (using the same SendGrid settings), which is working fine.

Many Thanks,

Andrew

**Comment by putyourlightson** [comment]
Hi Andrew, that's strange. Let me test with those plugins and I'll let you know what I find.

**Comment by putyourlightson** [comment]
Thanks Andrew, you were right, fixed in version 1.1.0 https://github.com/putyourlightson/craft-sendgrid/commit/0ca0f50eb7ec7f32331790008fd3d09083adb8da.

**Comment by afairhurst** [comment]
Hi Ben,

I’ve tried this, however still no joy.

No problem, as manual SendGrid SMTP config is working.

Thanks,

Andrew

**Comment by putyourlightson** [comment]
Are you saying that after updating to version 1.1.0 neither submissions though Contact Form nor Express Forms are coming through to your email account or the Sendgrid activity feed? I've tested extensively and the new version is working just fine in my tests.

**Comment by afairhurst** [comment]
Hi Ben,

Hold on... my bad. I’ve just double-checked and it seems it is working now.

Sorry, and thank you!

Andrew

**Comment by putyourlightson** [comment]
Glad to hear it!
