### ISSUE TITLE
Not working! There was an error testing your email settings! CRAFT 3.6.15

### ISSUE THREAD

**Issue by danieladarve** [putyourlightson/craft-sendgrid#11]
Hello,
The plugin is no longer working in the latest version of CraftCMS. 
When trying to test the configuration it returns:
 ```There was an error testing your email settings.```

I tested the sendgrid key using a lower version of craftcms and it works.

Also, following https://craftcms.com/knowledge-base/troubleshooting-email-errors
there are no error logs that can indicate what the issue is

I am currently Using Craft 3.6.15 and the latest version of the craft-sendgrid plugin

**Comment by bencroker** [comment]
Just tested locally with Craft 3.6.15 and it works as expected. Are you seeing nothing in any of the log files, even with `devMode` enabled?

**Comment by danieladarve** [comment]
Hi Ben,
I posted an issue in the craftrepo and no logs come up because swiftmailer
doesnt return the exception.

**Comment by bencroker** [comment]
Ok so are you saying the issue is with Craft core?

**Comment by danieladarve** [comment]
Hi Ben, as I mentioned, there are no logs generated, on any mode.
The craft development team advised this is because Swiftmailer eats up the exception.
So at the moment it is unknown why the error is occurring.
