### ISSUE TITLE
Error after updating Craft to and Sendgrid 1.3

### ISSUE THREAD

**Issue by AbbeyDesign** [putyourlightson/craft-sendgrid#13]
I get this error when sending a test email from the cp

`array_map(): Expected parameter 2 to be an array, string given`

and this error when email notifications are being sent through Freeform plugin

`array_map(): Expected parameter 2 to be an array, string given {"template":"taskNotification","file":"/xxx/xxx/xxx/xxx//vendor/putyourlightson/craft-sendgrid/src/mail/SendgridAdapter.php"} [] `

### Versions
- Plugin version: 1.30
- Craft version: 3.7.41

**Comment by bencroker** [comment]
Thanks for reporting, fixed in https://github.com/putyourlightson/craft-sendgrid/commit/2df08c3829419d113f92882cb8e9937c85a49fef for the next release.

**Comment by bencroker** [comment]
Released in version 1.3.1.
