### ISSUE TITLE
Sendgrid Adaptor keeps throwing me the error

### ISSUE THREAD

**Issue by pbmills** [putyourlightson/craft-sendgrid#14]
Please provide a clear and concise question. We are diligent about documentation, so please check whether your question is answered by the plugin docs before submitting.

2022-07-15 14:56:06 [-][995][-][warning][sendgrid] {"errors":[{"message":"The requestor's IP Address is not whitelisted","field":null,"help":null}]}

My IP is already Whitelisted in the sendgrid account. I keep getting this error. Please help me

**Comment by bencroker** [comment]
The error message is quite clear, not sure there's anything I can do to help you with whitelisting IP addresses.

**Comment by pbmills** [comment]
The IP addresses is already whitelisted. 😒


Regards,


Priti Burfield-Mills


M: 0220443081

W: https://burfieldmills.com

________________________________

**Comment by bencroker** [comment]
Yes, you mentioned that. I'm sure Sendgrid can provide support for your account.
