### ISSUE TITLE
Activation e-mail

### ISSUE THREAD

**Issue by benedikte-vdw** [putyourlightson/craft-sendgrid#16]
### Bug Report

Hello,

Sending e-mails from the back-end results in error message eg Sending an activation URL to a user is resulting in an ‘internal server error’ message.

Once a user is set to 'active' manually and sending a password reset e-mail from the login screen, works fine.

This is the error message from the storage/logs

`2024-11-11 15:12:56 [web.ERROR] [TypeError] putyourlightson\sendgrid\mail\SendgridTransport::__construct(): Argument #1 ($key) must be of type string, null given, called in /home/arteveldehs/webapps/arteveldehs/vendor/putyourlightson/craft-sendgrid/src/mail/SendgridAdapter.php on line 71 {"trace":["#0 /home/arteveldehs/webapps/arteveldehs/vendor/putyourlightson/craft-sendgrid/src/mail/SendgridAdapter.php(71): putyourlightson\\sendgrid\\mail\\SendgridTransport->__construct()","#1 /home/arteveldehs/webapps/arteveldehs/vendor/craftcms/cms/src/helpers/App.php(1050): putyourlightson\\sendgrid\\mail\\SendgridAdapter->defineTransport()","#2 /home/arteveldehs/webapps/arteveldehs/config/app.php(31): craft\\helpers\\App::mailerConfig()","#3 [internal function]: craft\\services\\Config->{closure}()","#4 /home/arteveldehs/webapps/arteveldehs/vendor/yiisoft/yii2/di/Container.php(633): call_user_func_array()","#5 /home/arteveldehs/webapps/arteveldehs/vendor/yiisoft/yii2/BaseYii.php(349): yii\\di\\Container->invoke()","#6 /home/arteveldehs/webapps/arteveldehs/vendor/yiisoft/yii2/di/ServiceLocator.php(137): yii\\BaseYii::createObject()","#7 /home/arteveldehs/webapps/arteveldehs/vendor/yiisoft/yii2/base/Module.php(766): yii\\di\\ServiceLocator->get()","#8 /home/arteveldehs/webapps/arteveldehs/vendor/craftcms/cms/src/web/Application.php(369): yii\\base\\Module->get()","#9 /home/arteveldehs/webapps/arteveldehs/vendor/craftcms/cms/src/base/ApplicationTrait.php(1299): craft\\web\\Application->get()","#10 /home/arteveldehs/webapps/arteveldehs/vendor/craftcms/cms/src/services/Users.php(474): craft\\web\\Application->getMailer()","#11 /home/arteveldehs/webapps/arteveldehs/vendor/craftcms/cms/src/controllers/UsersController.php(617): craft\\services\\Users->sendPasswordResetEmail()","#12 [internal function]: craft\\controllers\\UsersController->actionSendPasswordResetEmail()","#13 /home/arteveldehs/webapps/arteveldehs/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()","#14 /home/arteveldehs/webapps/arteveldehs/vendor/yiisoft/yii2/base/Controller.php(178): yii\\base\\InlineAction->runWithParams()","#15 /home/arteveldehs/webapps/arteveldehs/vendor/yiisoft/yii2/base/Module.php(552): yii\\base\\Controller->runAction()","#16 /home/arteveldehs/webapps/arteveldehs/vendor/craftcms/cms/src/web/Application.php(350): yii\\base\\Module->runAction()","#17 /home/arteveldehs/webapps/arteveldehs/vendor/craftcms/cms/src/web/Application.php(649): craft\\web\\Application->runAction()","#18 /home/arteveldehs/webapps/arteveldehs/vendor/craftcms/cms/src/web/Application.php(312): craft\\web\\Application->_processActionRequest()","#19 /home/arteveldehs/webapps/arteveldehs/vendor/yiisoft/yii2/base/Application.php(384): craft\\web\\Application->handleRequest()","#20 /home/arteveldehs/webapps/arteveldehs/web/index.php(12): yii\\base\\Application->run()","#21 {main}"],"memory":4695024,"exception":"[object] (TypeError(code: 0): putyourlightson\\sendgrid\\mail\\SendgridTransport::__construct(): Argument #1 ($key) must be of type string, null given, called in /home/arteveldehs/webapps/arteveldehs/vendor/putyourlightson/craft-sendgrid/src/mail/SendgridAdapter.php on line 71 at /home/arteveldehs/webapps/arteveldehs/vendor/putyourlightson/craft-sendgrid/src/mail/SendgridTransport.php:20)"}`

### Plugin Version

3.0.0

### Craft CMS Version

Craft Pro 5.4.10.1

### PHP Version

8.3.12

**Comment by benedikte-vdw** [comment]
not an issue, but config error

**Comment by bencroker** [comment]
Glad to hear you figure it out!
