### ISSUE TITLE
Sync error.

### ISSUE THREAD

**Issue by thefubon** [putyourlightson/craft-sendgrid#5]
![photo_2020-02-12_17-08-58](https://user-images.githubusercontent.com/43171309/74342401-7cb95d00-4dba-11ea-96c6-ffc91ef7ff92.jpg)

Please tell me how to configure SandMail correctly, I have an error

**Comment by thefubon** [comment]
which option you need to choose to generate the key, I have a node.js

**Comment by bencroker** [comment]
This plugin is for [Sendgrid](https://sendgrid.com), what exactly is your issue?
