### ISSUE TITLE
Email category

### ISSUE THREAD

**Issue by CMeldgaard** [putyourlightson/craft-sendgrid#6]
Is there any plans on integration categories to the email settings? I have a sendgrid account, thats used to different sites, and would very nice to be able to group them into categories.

**Comment by bencroker** [comment]
Do you perhaps mean something like https://github.com/craftcms/cms/issues/4594? This kind of change would need to be made to Craft rather than this plugin.

**Comment by CMeldgaard** [comment]
No, what i mean is, that when sending via SendGrid you can add an category to the email.

On the sendgrid i have different websites (all in unique Craft installations). So to make viewing stats for each site more easy, i need to be able add an category, which gets sent with the API request.

And the category field is available on the send api. This way i can could name a category based on the site, and then in sendgrid view send stats for each site.

**Comment by bencroker** [comment]
Oh I see, you mean this:
https://sendgrid.com/docs/API_Reference/SMTP_API/categories.html

So would you want to be able to set a single category that will be used for all emails sent through Craft?

**Comment by CMeldgaard** [comment]
For me that would be enough, that it has one base category

**Comment by bencroker** [comment]
Ok, I'll mark this as a feature request.

**Comment by CMeldgaard** [comment]
Is there any timeline on this?

**Comment by bencroker** [comment]
Added in https://github.com/putyourlightson/craft-sendgrid/commit/885c5a1628bd270634b87b83341990b533df2856 for the next release. Feel free to test it out already.

**Comment by bencroker** [comment]
Released in version 1.3.0.
